services:
  wdgb:
    build:
      context: .
      dockerfile: wikidata_graph_builder/Dockerfile
    container_name: wikidata_graph_builder
    env_file:
      - configs/wdgb.env
    environment:
      - APP_DUMPFILES_DIR=${WIKIDATA_DUMPS_PATH}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://wiki-es-pg:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=${NEO4J_USER}
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=${NEO4J_PASSWORD}
    depends_on:
      neo4j:
        condition: service_healthy
      postgres:
        condition: service_healthy
    links:
      - neo4j
      - postgres
    volumes:
      - wikidata-dumps:${WIKIDATA_DUMPS_PATH}
    networks:
      - wiki-es-network
  wpap:
    build:
      context: .
      dockerfile: wikipedia_abstract_processor/Dockerfile
    container_name: wikipedia_abstract_processor
    env_file:
      - configs/wpap.env
    depends_on:
      neo4j:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - wikidata-dumps:/app/dump-files
    networks:
      - wiki-es-network

  postgres:
    hostname: wiki-es-pg
    image: 'postgres:latest'
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U ${DB_USER}
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - configs/pg.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - wiki-es-network

  neo4j:
    hostname: wiki-es-neo
    image: 'neo4j:5'
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "neo4j", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - configs/neo4j.env
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - neo4j-data:/data
    ports:
      - '7474:7474'
      - '7687:7687'
    networks:
      - wiki-es-network

  jupyter:
    image: jupyter/minimal-notebook
    hostname: wiki-es-jupyter
    volumes:
      - jupyter-data:/home/jovyan/work
    env_file:
      - configs/jupyter.env
    environment:
      - DOCKER_STACKS_JUPYTER_CMD=notebook
      - NOTEBOOK_ARGS="--NotebookApp.token='${JUPYTER_TOKEN}'"
    restart: unless-stopped
    ports:
      - '8888:8888'
    container_name: jupyter_notebook
    networks:
      - wiki-es-network

networks:
  wiki-es-network:
    external: true

volumes:
  postgres-volume:
    driver: local
    driver_opts:
      type: none
      device: ${POSTGRES_VOLUME_PATH}
      o: bind
  neo4j-data:
    driver: local
    driver_opts:
      type: none
      device: ${NEO4J_VOLUME_PATH}
      o: bind

  jupyter-data:
    driver: local
    driver_opts:
      type: none
      device: ${JUPYTER_VOLUME_PATH}
      o: bind

  wikidata-dumps:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${WIKIDATA_DUMPS_PATH}
  wiki-es-output:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${OUTPUT_VOLUME_PATH}